language: go

cache:
  directories:
  - $GOPATH/pkg/mod/cache

go:
  - "1.11.13"
  - "1.12.9"
  - "1.13rc2"

branches:
  only:
    - master

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - os: linux
      go: "1.13rc2"
      env: CHECK_GOFMT=1

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

go_import_path: github.com/myitcv/gobin

# Add this before_install until we have a definitive resolution on
# https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349/2
before_install:
  - cd ../..
  - mv $TRAVIS_REPO_SLUG _old
  - git config --global core.autocrlf false
  - git clone --depth=50 _old $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG

install: "echo no install step required"

before_script:
  - git config --global core.excludesfile ~/.gitignore_global
  - echo ".gobincache" >> ~/.gitignore_global

script:
  - go test ./...

    # ensure we can install the "old" way (which will again use vendor)
  - GO111MODULE=off go install

  - go mod vendor
  - go mod tidy

    # https://github.com/golang/go/issues/27868#issuecomment-431413621
  - go list all > /dev/null

    # TODO re-enable once we can sort secrets on Windows and when we have re-added the
    # dependency on myitcv.io (https://github.com/golang/go/issues/29773); then we can work
    # out what Docker strategy we need/want
    #
    # - go run github.com/myitcv/gobin -m -run myitcv.io/cmd/mdreplace -long -online -w README.md
    # - gobin -m -run myitcv.io/cmd/mdreplace -w README.md

    # Go 1.13 fixed the sorting of vendor/modules.txt. However, this breaks our
    # check on prior versions of Go that are in the build matrix. Hence, apply
    # known diffs to satisfy the git status check.
  - ./_scripts/apply_known_diffs.sh

  - if [[ -n $CHECK_GOFMT ]]; then diff <(echo -n) <(gofmt -d .); fi
  - test -z "$(git status --porcelain)" || (git status; git diff; false)
