language: go
env:
  - GO111MODULE=on
go_import_path: github.com/myitcv/gobin
go:
  - "1.11.x"
before_script:
  - git config --global core.excludesfile ~/.gitignore_global
  - echo ".gobincache" >> ~/.gitignore_global
install: "echo no install step required"
script:
  - go test ./...

    # ensure we can install the "old" way (which will again use vendor)
  - GO111MODULE=off go install

  - go mod vendor
  - go mod tidy

    # https://github.com/golang/go/issues/27868#issuecomment-431413621
  - go list all > /dev/null
  - go run github.com/myitcv/gobin -m -run myitcv.io/cmd/mdreplace -long -online -w README.md
  - test -z "$(git status --porcelain)" || (git status; git diff; false)
